import random 
import string

"""
	Random String Manager should garunte the random strings used are unique for all string 
	generated by this object 
"""
class RandomStringManager(object):
	def __init__(self):
		self.randomStrings = []
	
	"""
		Generate a random string of fixed length 
		Assures the string generated has not been generated before in this object's lifespan
	
	params:
		int stringLength: 
			Length of the string
	return:
		a unique, random string 

	"""
	def getString(self, stringLength=10):
		letters = string.ascii_lowercase
		random_string = ''.join(random.choice(letters) for i in range(stringLength))
		while random_string in self.randomStrings:
			random_string = ''.join(random.choice(letters) for i in range(stringLength))

		self.randomStrings.append(random_string)
		return random_string
